# Generated by Django 6.0.6 on 2026-09-15 17:47

import televisores.validadores
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('televisores', '0013_alter_televisor_serial_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='televisor',
            name='mac_address',
            field=models.CharField(max_length=50, unique=True, validators=[televisores.validadores.validar_mac], verbose_name='Dirección MAC'),
        ),
    ]
